name: GetraenkeIO-Backend tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r sys-src/GetraenkeIO-backend/requirements.txt
    - name: Copy .env File
      run: cp sys-src/GetraenkeIO-backend/.env.example .env
    - name: Test with pytest and coverage
      run: |
        pip install pytest coverage
        coverage run -m pytest sys-src/GetraenkeIO-backend/
    - name: Show coverage report
      run: coverage report --omit="*\tests\*"